# standard jekyll config

permalink: date
highlighter: rouge
markdown: kramdown
github: [metadata]
exclude: ['README.md', 'Gemfile' , 'Gemfile.lock']
title: "Dylan Martin"
author: "Dylan"
description: "Blogging and curating content about tech, programming, finance, politics, business, and culture"
url: "https://www.dylanamartin.com"
future: true

collections:
  digest:
    output: true

feed:
  collections:
    digest:
      path: "/digest.xml"
    posts:
      path: "/blog.xml"

repository: dmarticus/dmarticus.github.io
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-analytics

Matomo:
  url: https://dylanamartin.matomo.cloud
  siteId: "1"